### ISSUE TITLE
OccResponse in occurrences

### ISSUE THREAD

**Issue by Ei3-kw** [iobis/pyobis#171] opened 2024-12-09 23:27 UTC
Hi, 

It seems to me that `execute()` in `OccResponse` gives out the results data straight away instead of `{'total': int, 'results': dict}`, which voids the `to_pandas()` function. 
<img width="769" alt="Screenshot 2024-12-10 at 10 27 01" src="https://github.com/user-attachments/assets/387f287d-16c0-4c9f-ad5c-d2ff0e2cdff4">

This is inconsistent with provided documentation as well as other classes.

Also is there a way to get all the `nodeid`s

Cheers, Ella

**Comment by ayushanand18** [comment] 2024-12-11 09:03
Hey, thanks for raising this. For users ease execute() method throws a pandas dataframe and sets the data in the 'data' attribute. so you can use object.data to access it later on. The  to_pandas method also exists on the OccResponse object and not a DF - so the error popped up.

**Comment by ayushanand18** [comment] 2024-12-11 14:44
on another note, you should ideally create an object using occurrences.search() and do an execute() using object.execute(). This will allow you to play around with the data, do necessary transformations without having to refetch if you do some modifications (fetched result is also stored in as object.data). Everytime you call .search() - it creates a new object, and you might end up frequently refetching data.

**Comment by 7yl4r** [comment] 2024-12-12 17:21
Hi @Ei3-kw , 

Can you provide some more code with comments indicating what you are trying to do?

**Comment by Ei3-kw** [comment] 2024-12-13 00:49
I am calling `to_pandas()` on `OccResponse` object

```py
from pyobis import occurrences

# search up OBIS JP node
df = occurrences.search(nodeid='0d07a0ea-9c75-48e8-b3fd-c28d653f4270', size=69)
fetched = df.execute() # fetch the db
print(f"Columns in the fetched Dataframe: {fetched.columns}")
df.to_pandas()```

But fetched data, which's stored as `self._data` is already the value of results, which caused `to_pandas()` to fail. Bc it's expecting {'total': int, 'results': dict}.

The columns of fetched data
```Columns in the fetched Dataframe: Index(['associatedMedia', 'basisOfRecord', 'catalogNumber', 'class',
       'collectionCode', 'datasetName', 'day', 'decimalLatitude',
       'decimalLongitude', 'endDayOfYear',
       ...
       'county', 'parvphylum', 'gigaclass', 'parvphylumid', 'gigaclassid',
       'maximumDistanceAboveSurfaceInMeters',
       'minimumDistanceAboveSurfaceInMeters', 'subgenus', 'subgenusid',
       'georeferenceRemarks'],
      dtype='object', length=150)
```

I've got around it by using the fetched data straight away and calling  `len` to get the total. But it is inconsistent with provided documentation and how other classes behave.

Cheers, Ella

**Comment by ayushanand18** [comment] 2024-12-14 06:43
Thanks for the code snippet. I was able to reproduce this. 

Sorry for the issue. We probably thought people would be directly using the `query.data` object to use the dataframe for search queries, but you have a fair point - all library methods must be consistent.

**Comment by ayushanand18** [comment] 2024-12-16 15:21
reopening this so that we make a patch release. cc @7yl4r

**Comment by ocefpaf** [comment] 2024-12-17 18:49
> I don't see a GH action to push to conda forge. Do we need to set one up or is there another process for pushing to conda?

Conda-forge has a bot that does that for you based on the PyPI release. We don't need to do anything.

**Comment by ayushanand18** [comment] 2024-12-18 03:02
conda forge has 1.3.1, seems like they aren't updated since last two releases. 👀

**Comment by ayushanand18** [comment] 2024-12-18 03:04
meanwhile, @Ei3-kw you can upgrade the package from pypi and it should be resolved.

**Comment by ocefpaf** [comment] 2024-12-18 09:12
> conda forge has 1.3.1, seems like they aren't updated since last two releases. 👀

That is odd. But this one is there: https://github.com/conda-forge/pyobis-feedstock/pull/3

**Comment by ayushanand18** [comment] 2024-12-19 02:35
It got updated, ig the pr wasn't merged before I checked or the CI job took some time. Looks good.

**Closed** 2024-12-19 02:37 UTC
